<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="43484c456ae3" failures="1" tests="5" name="Flight Reservation Tests for one passenger" time="11.538" errors="0" timestamp="2025-05-18T10:51:32 GMT">
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="userRegistrationTest" time="1.881"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="registrationConfirmationTest" time="2.432"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="flightSearchTest" time="2.556"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="selectFlightsTest" time="1.446"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="flightConfirmationTest" time="0.731">
    <failure type="java.lang.AssertionError" message="expected [$5840 USD] but found [$584 USD]">
      <![CDATA[java.lang.AssertionError: expected [$5840 USD] but found [$584 USD]
at org.seleniumdocker.tests.FlightReservation.FlightReservationTests.flightConfirmationTest(FlightReservationTests.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- flightConfirmationTest -->
</testsuite> <!-- Flight Reservation Tests for one passenger -->
