<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="43484c456ae3" failures="1" tests="5" name="Flight Reservation Tests for four passenger" time="7.488" errors="0" timestamp="2025-05-18T10:51:38 GMT">
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="userRegistrationTest" time="1.457"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="registrationConfirmationTest" time="0.751"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="flightSearchTest" time="1.428"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="selectFlightsTest" time="0.8"/>
  <testcase classname="org.seleniumdocker.tests.FlightReservation.FlightReservationTests" name="flightConfirmationTest" time="2.295">
    <failure type="java.lang.AssertionError" message="expected [$23380 USD] but found [$2338 USD]">
      <![CDATA[java.lang.AssertionError: expected [$23380 USD] but found [$2338 USD]
at org.seleniumdocker.tests.FlightReservation.FlightReservationTests.flightConfirmationTest(FlightReservationTests.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- flightConfirmationTest -->
</testsuite> <!-- Flight Reservation Tests for four passenger -->
